/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.SettingDAO;
import control.Validate;
import javax.swing.JOptionPane;
import model.Setting;

/**
 *
 * @author duong
 */
public class SettingForm extends javax.swing.JFrame {
    public Setting setting;
    /**
     * Creates new form SettingForm
     */
    public SettingForm() {
        initComponents();
        setEditable(false);
        init();
        
        
    }
    public void init(){
        setting = new SettingDAO().getSetting();
        showSetting();
    }
    public void showSetting(){
        this.jTextField_bh1.setText(setting.getBh1()+"");
        this.jTextField_hotro1.setText(setting.getHotro1()+"");
        this.jTextField_hotro2.setText(setting.getHotro2()+"");
        this.jTextField_hotro3.setText(setting.getHotro3()+"");
    }
    public boolean validateSetting() {
        return Validate.validatePercent(this.jTextField_bh1.getText(), "(1)")
                && Validate.validatePercent(this.jTextField_hotro1.getText(), "(2)")
                && Validate.validatePercent(this.jTextField_hotro2.getText(), "(3)")
                && Validate.validatePercent(this.jTextField_hotro3.getText(), "(4)");
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_bh1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_hotro1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_hotro2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_hotro3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton_sua = new javax.swing.JButton();
        jButton_apdung = new javax.swing.JButton();
        jButton_thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cấu hình các thông số");

        jLabel2.setText("Phần thu nhập tháng:");

        jLabel3.setText("Hỗ trợ diện hộ nghèo:");

        jLabel4.setText("Hỗ trợ diện HS/SV:");

        jLabel5.setText("Hỗ trợ hộ nông:");

        jLabel6.setText("%");

        jTextField_hotro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_hotro1ActionPerformed(evt);
            }
        });

        jLabel7.setText("% *");

        jLabel8.setText("% *");

        jLabel9.setText("% *");

        jLabel10.setText("(% thu nhập tháng tính tiền BH)");

        jLabel11.setText(" * (% thu nhập theo tháng nhà nước hỗ trợ BH)");

        jButton_sua.setText("Sửa");
        jButton_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suaActionPerformed(evt);
            }
        });

        jButton_apdung.setText("Áp dụng");
        jButton_apdung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_apdungActionPerformed(evt);
            }
        });

        jButton_thoat.setText("Thoát");
        jButton_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_bh1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_hotro1)
                                    .addComponent(jTextField_hotro2)
                                    .addComponent(jTextField_hotro3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton_sua)
                        .addGap(84, 84, 84)
                        .addComponent(jButton_apdung)
                        .addGap(69, 69, 69)
                        .addComponent(jButton_thoat)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_bh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_hotro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_hotro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_hotro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_sua)
                    .addComponent(jButton_apdung)
                    .addComponent(jButton_thoat))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_hotro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_hotro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_hotro1ActionPerformed

    private void jButton_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suaActionPerformed
        // TODO add your handling code here:
        setEditable(true);
        this.jButton_sua.setVisible(false);
        this.jButton_apdung.setVisible(true);
    }//GEN-LAST:event_jButton_suaActionPerformed

    private void jButton_apdungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_apdungActionPerformed
        // TODO add your handling code here:
        if (validateSetting()) {
            int c = JOptionPane.showConfirmDialog(this, "Bạn muốn áp dụng?");
            if (c == JOptionPane.YES_OPTION) {
                SettingDAO sd = new SettingDAO();
                setting = new Setting(Float.parseFloat(jTextField_bh1.getText()),
                        Float.parseFloat(jTextField_hotro1.getText()),
                        Float.parseFloat(jTextField_hotro2.getText()),
                        Float.parseFloat(jTextField_hotro3.getText()));
                       
                sd.addSetting(setting);
            } else {
                showSetting();
            }
            this.jButton_sua.setVisible(true);
            this.jButton_apdung.setVisible(false);
            this.jButton_thoat.setVisible(true);
            setEditable(false);
        }
        
    }//GEN-LAST:event_jButton_apdungActionPerformed

    private void jButton_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thoatActionPerformed
        // TODO add your handling code here:
        SettingForm sf= new SettingForm();
        MainForm mf= new MainForm();
        sf.setVisible(false);
        mf.setVisible(true);
        sf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_thoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_apdung;
    private javax.swing.JButton jButton_sua;
    private javax.swing.JButton jButton_thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField_bh1;
    private javax.swing.JTextField jTextField_hotro1;
    private javax.swing.JTextField jTextField_hotro2;
    private javax.swing.JTextField jTextField_hotro3;
    // End of variables declaration//GEN-END:variables

    private void setEditable(boolean b) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.jTextField_bh1.setEditable(b);
        this.jTextField_hotro1.setEditable(b);
        this.jTextField_hotro3.setEditable(b);
        this.jButton_apdung.setVisible(b);
//        this.jButton_thoat.setVisible(b);
    }
}
